### ISSUE TITLE
Download report button doesn't seem function correctly, downloaded image failed open 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#10]

**Comment by ajinabraham** [comment]
Known issue. If the page is very large, HTML2IMG conversion fails. Issues with html2canvas library. As a work around you can press Ctrl+P and save the page as a PDF. I am looking for other alternatives to make a better report without much effort.

**Comment by bugwrangler** [comment]
Okay, that's fine!

**Comment by bugwrangler** [comment]
Does it fix ?

**Comment by ajinabraham** [comment]
Not working on this currently. Adding functionalities like iOS static code analysis these days.

**Comment by bugwrangler** [comment]
okay fine, would be cool to have PDF rather than Image. however it's not core necessity!

**Comment by ajinabraham** [comment]
Ya I have plans for PDF/HTML files.

**Comment by bugwrangler** [comment]
Issue is with image download button fow now hence closing this. thank you!
