### ISSUE TITLE
[Check] Does this framework verify app that app has rooted detection mechanism or not ?

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#16]

**Comment by ajinabraham** [comment]
I did not have a generic set of code for root detection. How ever I will be adding signatures of SuperSu and DexGuard for root detection and couple of other functionalities.

**Comment by ajinabraham** [comment]
Added DexGuard Root detection and Custom Root Request detection in v0.7beta. If you can share some signatures that will be helpful.
