### ISSUE TITLE
Framework should also support upload Core code zip upload w.r.t Scenario bug #20

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#21]
Static analysis should be possible if user upload the code zip

**Comment by ajinabraham** [comment]
I could not understand your question. The Framework support zipped source code in Andoid Studio and eclipse.

**Comment by bugwrangler** [comment]
Allow use to upload .zip code file at framework, right not framework supports only APK right?

**Comment by ajinabraham** [comment]
No Framework supports Zipped Source (Android Studio & Eclipse Project Files)

**Comment by bugwrangler** [comment]
Wouldn't it help - Just to understand stuff using direct code? lets take example of Bug #20 
I am not sure if i am really making sense here or not

**Comment by ajinabraham** [comment]
Please be specific here. I am not getting it.

**Comment by bugwrangler** [comment]
So let say code is not reversible and want to do static analysis - if there is option to upload the direct build code zip - static analysis can be done on code directly/

So i feel that - there should be option to upload code without .apk

**Comment by ajinabraham** [comment]
Yes I already mentioned that Mobile Security Framework Supports Static Analysis on Source code.
It supports two common IDE project files as of now Android Studio and Eclipse.

Go to the directory where you have the project files, select all zip it and upload it to the Framework for Static Analysis.

**Comment by bugwrangler** [comment]
So sorry, I didn't try and confused by your statement - Cool :+1:
