### ISSUE TITLE
[Google Chrome - Win7] Progress bar doesn't display fix align below the upload & Analyse button

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#27]
![progress bar](https://cloud.githubusercontent.com/assets/6933052/7445896/635ef78a-f1e3-11e4-990f-fb77b3a541ee.png)

**Comment by ajinabraham** [comment]
The UI will be changed including Progress Bar Soon!

**Comment by bugwrangler** [comment]
aha look forward to see updated view ~
