### ISSUE TITLE
Progress bar doesn't render in FF & IE11 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#28]
![progress bar - ff ie](https://cloud.githubusercontent.com/assets/6933052/7445935/8cdf30ba-f1e4-11e4-9e8c-95990c1a9b5e.png)

**Comment by bugwrangler** [comment]
i guess it's known issue with Windows OS

**Comment by ajinabraham** [comment]
Known issue with FF and IE. This will be fixed on UI Change.

**Comment by bugwrangler** [comment]
Okay fine ~

**Comment by ajinabraham** [comment]
Fixed this on v0.8.4beta release.
