### ISSUE TITLE
Unicode decoding error 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#29]
Try with following APK(s) : 
com.irccloud.android  
com.irctc.main

![unicode decoding error](https://cloud.githubusercontent.com/assets/6933052/7446892/4819dd88-f205-11e4-9a9a-35e7186f1757.png)

**Comment by ajinabraham** [comment]
Looks like file encoding type is causing this issue. Investigating more on this.

**Comment by ajinabraham** [comment]
Are you using the latest release https://github.com/ajinabraham/YSO-Mobile-Security-Framework/releases ?

Working fine for me.

**Comment by bugwrangler** [comment]
yes working on latest build only, let me try on Mac

**Comment by ajinabraham** [comment]
It doesn't matter actually. Give me the  MD5 hash of the APK you are using.

**Comment by bugwrangler** [comment]
com.irctc.main-12.apk&type=apk&checksum=e946256a4268e64c819f54fbbcec1f6f

**Comment by bugwrangler** [comment]
I hope checksum and package name will help you to identify the App

**Comment by ajinabraham** [comment]
Working perfectly fine for me.
![screen shot 2015-05-07 at 12 25 34 pm](https://cloud.githubusercontent.com/assets/4301109/7509920/3cc8ab10-f4b4-11e4-894b-37c82e9bb76d.png)

**Comment by ajinabraham** [comment]
@bugwrangler any update on this?

**Comment by bugwrangler** [comment]
Will update you by tomorrow, AF windows machine since 1 week ~ 
It doesn't replicate at my Mac M/C, there are one more work item pending at my bucket - will update you.

**Comment by odan77** [comment]
Error , why fix it ?

![screenshot from 2015-05-14 20 37 15](https://cloud.githubusercontent.com/assets/10478563/7646533/a68ca4aa-fa79-11e4-9445-3b47da2a73aa.png)

**Comment by odan77** [comment]
already fixed, I had not yet update the java to java 7: D, then I update it:
sudo update-alternatives --config java

**Comment by bugwrangler** [comment]
Now, System goes into infinite process and doesn't show any error as such :  com.yahoo.mobile.client.android.mail.apk 
 
![screen shot 2015-05-25 at 7 16 45 pm](https://cloud.githubusercontent.com/assets/6933052/7798067/b45a4d52-0312-11e5-90d9-1815532b5a20.png)

**Comment by ajinabraham** [comment]
Looks like my fix for Regex DoS caused another one.
Can you provide the APK or playstore link and md5 hash.

**Comment by bugwrangler** [comment]
MD5 (com.yahoo.mobile.client.android.mail.apk) = d6225641b1fed864d8763ab3f4ed0092

**Comment by ajinabraham** [comment]
Fixed the issue. It was a catastrophic backtracking in URL extraction regex. Replaced it with my custom regex. commit: https://github.com/ajinabraham/YSO-Mobile-Security-Framework/commit/d734ca99f9203ca4f93eee91bdab79cd2721d4ce

New Release is not created.
