### ISSUE TITLE
details about the VM used

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/YSO-Mobile-Security-Framework#3]
as evident there is a VM used for dynamic analysis.

It would be counter productive to share the entire vm but a setup script to do that would be great.

**Comment by ajinabraham** [comment]
I have plans to host it somewhere else so that you can access the complete source code including the VM. The VM is custom developed which need some modifications and extra installations, So script setup won't work here.

**Comment by bugwrangler** [comment]
I assume that this not applicable for this release, correct me if I'm thinking wrong.

**Comment by ajinabraham** [comment]
It's a custom VM. Can't upload it to GitHub due to size restrictions. Working on few other things on Dynamic Analyzer. Will host this as a project with full documentation and the VM in near future.

**Comment by bugwrangler** [comment]
Cool - thanks for information!
