### ISSUE TITLE
Any option to stop Server [Query] 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#31]
python manage.py stopserver {}... 

Any option is available like this ?

**Comment by ajinabraham** [comment]
Ctrl + C will kill the server gracefully.
These are the commands available under manage.py

in-mac-02:YSO-Mobile-Security-Framework aabraham$ python manage.py 

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    runfcgi
    shell
    showmigrations
    sql
    sqlall
    sqlclear
    sqlcustom
    sqldropindexes
    sqlflush
    sqlindexes
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    syncdb
    test
    testserver
    validate

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

**Comment by bugwrangler** [comment]
Thanks ~ It helps :+1:
