### ISSUE TITLE
How can i contribute to the framework w.r.t new definition [Query] 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#32]
Lets take example - i have python script and wanted to add some new updates in code review.
Can i have any sample example w.r.t framework so i can provide accordingly and commit the same. 

Basically I am talking about code scalability

**Comment by ajinabraham** [comment]
I was thinking to move the rules for Static Analysis to an xml file so that any one can add rules to it.
As of now you have to specify it on StaticAnalyzer.py

Now if you need to add some rules, you can comment it here and If suitable, I can add it to the framework.
