### ISSUE TITLE
Static Analyzer doesn't work

### ISSUE THREAD

**Issue by dummyusergit** [ajinabraham/YSO-Mobile-Security-Framework#34]
Hello!

I've tried to install and play a bit with YSO in an xubuntu vm, but I couldn't make it work. My setup:

Python 2.7.8, django 1.8a1, openjdk version "1.8.0_40-internal"

The server runs, but when I upload an apk nothing happens. Is there any log file to help me troubleshoot? Is there any info that I can provide regarding my setup to help you guide me to fix the problem?

Many thanks!

**Comment by bugwrangler** [comment]
Which browser are you trying this?

**Comment by bugwrangler** [comment]
There is one known issue with progress bar, wait for while and check the status bar under the browser. 
FF / IE / Safari doesn't show progress bar and it looks like - there is no progress but there is process going on ~ 

Logs are generating at terminal, kindly have a look for debugging. 

Further to this - Please provide terminal screenshot & manage.py for debug!

**Comment by dummyusergit** [comment]
the browser is FF
I'll try again and I'll wait looking at the terminal for any message.

many thanks for the prompt response!

**Comment by dummyusergit** [comment]
uploaded an apk:

System check identified no issues (0 silenced).
May 11, 2015 - 19:36:10
Django version 1.8a1, using settings 'YodleeMobSec.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[11/May/2015 19:36:23]"GET / HTTP/1.1" 200 4314
[11/May/2015 19:36:23]"GET /static/css/cover.css HTTP/1.1" 200 2846
[11/May/2015 19:36:23]"GET /static/css/bootstrap.min.css HTTP/1.1" 200 109518
[11/May/2015 19:36:23]"GET /static/js/ie-emulation-modes-warning.js HTTP/1.1" 200 2132
[11/May/2015 19:36:23]"GET /static/js/jquery.min.js HTTP/1.1" 200 95786
[11/May/2015 19:36:23]"GET /static/img/logo.ico HTTP/1.1" 200 370070
[11/May/2015 19:36:23]"GET /static/js/bootstrap.min.js HTTP/1.1" 200 31819
[11/May/2015 19:36:23]"GET /static/js/ie10-viewport-bug-workaround.js HTTP/1.1" 200 694
[11/May/2015 19:36:23]"GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 200 23320
[11/May/2015 19:36:23]"GET /static/favicon.ico HTTP/1.1" 200 370070
[11/May/2015 19:36:53]"GET /static/img/loader.gif HTTP/1.1" 200 10819
[INFO] MIME Type: application/vnd.android.package-archive FILE: zzz.apk
[11/May/2015 19:36:53]"POST /Upload/ HTTP/1.1" 302 0
[11/May/2015 19:36:53]"GET / HTTP/1.1" 200 4314

**Comment by dummyusergit** [comment]
$ cat settings.py
"""
Django settings for YodleeMobSec project.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os,platform
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#r$=rg*lit&!4nukg++@%k+n9#6fhkv_*a6)2t$n1b=*wpvptl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'StaticAnalyzer',
    'DynamicAnalyzer',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'YodleeMobSec.urls'

WSGI_APPLICATION = 'YodleeMobSec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

MEDIA_URL = '/uploads/'


TEMPLATE_DIRS = (
    os.path.join(BASE_DIR,'templates'),
    )

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static/'),
)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

#CUSTOM SETTINGS

 
if platform.system()=="Windows":
    JAVA_PATH='C:/Program Files/Java/jdk1.7.0_17/bin/'  # Use "/" instead of "\" while setting the path.
    VBOX='C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' #Path to VBoxManage.exe
else:
#    JAVA_PATH='/usr/bin/' #For OSX and Linux
    JAVA_PATH='/usr/lib/jvm/java-8-openjdk-amd64/bin'
    VBOX='/usr/bin/VBoxManage' #For OSX and Linux

#VM SPECIFIC
#VBoxManage showhdinfo "d:\YSOMobSec\DynamicAnalyzer\tools\VM\sdcard.vdi"
UUID='a4a3b417-c8f1-41ba-9d00-9d6ab88d15d3'
SUUID='f6ccdff8-10df-460b-bba2-efa93e5a330b' #This Can Change 
#VM IP
VM_IP='192.168.56.101' #VM/Device IP
PROXY_IP='192.168.62.252' #Host/Server/Proxy IP
PORT='1337' #Proxy Port

**Comment by ajinabraham** [comment]
The path should be JAVA_PATH='/usr/lib/jvm/java-8-openjdk-amd64/bin/' instead of JAVA_PATH='/usr/lib/jvm/java-8-openjdk-amd64/bin'

Also don't you have java under /usr/bin/ ?

From the console log the issue looks strange to me.

The following code should get invoked after the APK is uploaded.
```
 print "[INFO] MIME Type: " + file_type + " FILE: " + str(request.FILES['file'].name)
            if (file_type=="application/octet-stream" or file_type=="application/vnd.android.package-archive") and request.FILES['file'].name.endswith('.apk'):     #APK
                md5=handle_uploaded_file(request.FILES['file'],'.apk')
                return HttpResponseRedirect('/StaticAnalyzer/?name='+request.FILES['file'].name+'&type=apk&checksum='+md5)  
```
Did you tried uploading zipped source code?

**Comment by ajinabraham** [comment]
I think you are using an old release. The issue was fixed in version 0.8.3.
Download the latest release and try again.
https://github.com/ajinabraham/YSO-Mobile-Security-Framework/releases/tag/0.8.3.

**Comment by dummyusergit** [comment]
apk check ended with:
```
System check identified no issues (0 silenced).
May 11, 2015 - 19:49:22
Django version 1.8a1, using settings 'YodleeMobSec.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
I fixed the path for java and now I'm trying again!

**Comment by dummyusergit** [comment]
ok, downloading latest release and checking again!

**Comment by dummyusergit** [comment]
it worked!!!

Many thanks for your help!!!!
