### ISSUE TITLE
 MANIFEST ANALYSIS  Popup & Activities doesn't wrap the text. 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#36]
![image](https://cloud.githubusercontent.com/assets/6933052/7798040/2eac2702-0312-11e5-8933-9fd6b7ba2b4a.png)
![screen shot 2015-05-25 at 6 54 33 pm](https://cloud.githubusercontent.com/assets/6933052/7798053/6c5a5e8e-0312-11e5-8759-d3601ff6a4c1.png)

**Comment by ajinabraham** [comment]
UI is a problem. I need some help here

**Comment by bugwrangler** [comment]
This has been fixed.
