### ISSUE TITLE
Try out com.pinterest.apk pacakge, latest build pushed into infinite process 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#40]
[INFO] MIME Type: application/octet-stream FILE: com.pinterest.apk
[10/Jul/2015 20:03:00]"POST /Upload/ HTTP/1.1" 200 140
[INFO] Starting Analysis on : com.pinterest.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR

<img width="527" alt="screen shot 2015-07-11 at 1 40 47 am" src="https://cloud.githubusercontent.com/assets/6933052/8628123/e7eeca74-276d-11e5-9f05-dac0498cc10e.png">

**Comment by ajinabraham** [comment]
Unable to reproduce this on v0.8.7beta
INFO] MIME Type: application/octet-stream FILE: com.pinterest.apk
[25/Jul/2015 18:29:30]"POST /Upload/ HTTP/1.1" 200 140
[INFO] Starting Analysis on : com.pinterest.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
dex2jar /Users/aabraham/YSO-Mobile-Security-Framework/uploads/bbb43be5fadcf779b280bf487b973f3c/classes.dex -> /Users/aabraham/YSO-Mobile-Security-Framework/uploads/bbb43be5fadcf779b280bf487b973f3c/classes.jar
[INFO] DEX -> SMALI
[INFO] JAR -> JAVA
Processing /Users/aabraham/YSO-Mobile-Security-Framework/uploads/bbb43be5fadcf779b280bf487b973f3c/classes.jar (use silent to silence)

**Comment by bugwrangler** [comment]
Will reproduce and update the result soon

**Comment by ajinabraham** [comment]
The process get stuck while using CFR decompiler.

-------SNIP--------------
Processing org.apache.thrift.protocol.TBinaryProtocol$Factory
Processing org.apache.thrift.protocol.TBinaryProtocol
Processing org.apache.thrift.protocol.TCompactProtocol$Factory
Processing org.apache.thrift.protocol.TCompactProtocol$Types
Processing org.apache.thrift.protocol.TCompactProtocol

This is an issue with CFR decompiler.

In settings.py, specify jd-core as the decompiler to use. This will fix the issues.
```
#CUSTOM SETTINGS
DECOMPILER = "jd-core" 

#Two Decompilers are available 
#1. jd-core
#2. cfr
```

Changing the decompiler to jd-core will fix this issue.

**Comment by bugwrangler** [comment]
Thank you, it worked out ~
