### ISSUE TITLE
Getting error after launching "http://127.0.0.1:8000/"

### ISSUE THREAD

**Issue by sunipa21** [ajinabraham/YSO-Mobile-Security-Framework#42]
Hi,

I am trying to setup "YSO mobile security framework"

Have installed jav, Django and pyhton
also have performed below commands 

python manage.py migrate
python manage.py runserver 127.0.0.1:8000

but when I am trying to launch "http://127.0.0.1:8000/"

getting below error

"SyntaxError at /
Missing parentheses in call to 'print' (views.py, line 9)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Django Version:	1.8.3
Exception Type:	SyntaxError
Exception Value:	
Missing parentheses in call to 'print' (views.py, line 9)
Exception Location:	C:\Python34\lib\importlib\__init__.py in import_module, line 109
Python Executable:	C:\Python34\python.exe
Python Version:	3.4.3
Python Path:	
['G:\\Security Testing\\YSO '
 'Mobile\\YSO-Mobile-Security-Framework-master\\YSO-Mobile-Security-Framework-master',
 'C:\\Windows\\system32\\python34.zip',
 'C:\\Python34\\DLLs',
 'C:\\Python34\\lib',
 'C:\\Python34',
 'C:\\Python34\\lib\\site-packages']
Server time:	Wed, 15 Jul 2015 15:06:36 +0530"

Please help me resolving this issue.

Note: 
1. I am using pyhton 3.4 and have updated all print "text" to print("Text") in view.py file
2. Have tried setting (DEBUG = False) and (ALLOWED_HOSTS = ['127.0.0.1'] ) in YodleeMobSec.settings.py file

**Comment by ajinabraham** [comment]
The readme here: https://github.com/ajinabraham/YSO-Mobile-Security-Framework/blob/master/README.md
clearly specify to use Python 2.7.
Also make sure that your java path is properly set in settings.py
