### ISSUE TITLE
Issue after uploading APK file

### ISSUE THREAD

**Issue by abhifate** [ajinabraham/YSO-Mobile-Security-Framework#43]
Hi team. 
Please refer the below error and suggest me the solution. 

 
![error](https://cloud.githubusercontent.com/assets/13364070/8720858/36b42672-2bd3-11e5-9496-e2fbc874cb72.JPG)

**Comment by ajinabraham** [comment]
Have you configured your JAVA Path properly.
Please refer the README. If problem still persists, send me the console logs and the contents of your settings.py
