### ISSUE TITLE
 Email panels should bifurcate invalid file type (Like image files etc.)

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#45]
<img width="611" alt="screen shot 2015-08-04 at 3 29 29 pm" src="https://cloud.githubusercontent.com/assets/6933052/9058311/c2f17c22-3abd-11e5-8f6f-f136d44d9919.png">
 
Expected result : Domain schema identification logic should be updated.

**Comment by ajinabraham** [comment]
The base Email Regex is based on the format

[String]@[String].[String]

You can take this as a false positive. As per email schema the above filenames matches. So it's difficult to separate them out.
