### ISSUE TITLE
[Suggestion - Enhancement] Save&Show reports

### ISSUE THREAD

**Issue by tachencko** [ajinabraham/YSO-Mobile-Security-Framework#49]
Save reports, once you do an analysis, the report can not be recovered .At least I can not find it.

PDF reports, and I have seen that you are working on it as dynamic analysis.

Good Joob!

**Comment by ajinabraham** [comment]
Once Static Analysis is done, you can download the report by clicking Download Report.
PDF support will be added later.

**Comment by ajinabraham** [comment]
PDF Reporting added on v.0.8.8 Beta
