### ISSUE TITLE
WindowsError at /StaticAnalyzer/ - on successfully Upload (Win7 64 - Python 2.7 - Java 1.8) 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#7]
[Error 2] The system cannot find the file specified
Request Method:	GET
Request URL:	http://127.0.0.1:9095/StaticAnalyzer/?name=in_startv_hotstar-69.apk&type=apk&checksum=9816563268dfb15105c41eef193f6ef5
Django Version:	1.8a1
Exception Type:	WindowsError
Exception Value:	
[Error 2] The system cannot find the file specified
Exception Location:	C:\Python27\lib\subprocess.py in _execute_child, line 882
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.0
Python Path:	
['C:\\YSO-Mobile-Security-Framework',
 'C:\\Windows\\system32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']
Server time:	Thu, 2 Apr 2015 17:42:29 +0530

![image](https://cloud.githubusercontent.com/assets/6933052/6963706/eb687cce-d95f-11e4-811e-def83250e4c8.png)

**Comment by bugwrangler** [comment]
Adding Java path for debug :+1: 

JAVA_PATH='C:/Program Files/Java/jdk1.8.0_40/bin' # remember about the /  ( not \)

**Comment by ajinabraham** [comment]
People are so careless :D

JAVA_PATH='C:/Program Files/Java/jdk1.8.0_40/bin'  You missed ending /. The correct value should be
JAVA_PATH='C:/Program Files/Java/jdk1.8.0_40/bin/'

**Comment by bugwrangler** [comment]
Super dude, it is fixed :)
