### ISSUE TITLE
Search pane doesn't work 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/YSO-Mobile-Security-Framework#9]
Search for the MD5 or SHA1 and observe the error. 

![image](https://cloud.githubusercontent.com/assets/6933052/6981831/d9b19fc6-da25-11e4-8301-03cde6a226ca.png)

**Comment by ajinabraham** [comment]
Feature not implemented. There is no point in search until the results are stored in the DB. Lot of other work has to be done. Once everything is complete, DB will be implemented and results will be available for search.

**Comment by bugwrangler** [comment]
Cool

**Comment by ajinabraham** [comment]
Removed in 0.7beta as feature is not implemented
